# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('cards', '0001_initial'), ('cards', '0002_card_see_also'), ('cards', '0003_auto_20161002_0532'), ('cards', '0004_auto_20161002_0622'), ('cards', '0005_auto_20161002_0632'), ('cards', '0006_deck_language'), ('cards', '0007_auto_20161002_1315'), ('cards', '0008_remove_deck_learning'), ('cards', '0009_deck_cards')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CardTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning', models.ManyToManyField(to=b'cards.CardTranslation')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('facebook_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('languages', models.ManyToManyField(to=b'cards.Language')),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Person'),
        ),
        migrations.AddField(
            model_name='cardtranslation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Language'),
        ),
        migrations.AddField(
            model_name='card',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Language'),
        ),
        migrations.AddField(
            model_name='card',
            name='see_also',
            field=models.ManyToManyField(blank=True, related_name='_card_see_also_+', to=b'cards.Card'),
        ),
        migrations.AddField(
            model_name='cardtranslation',
            name='literal',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='deck',
            name='learning',
        ),
        migrations.AddField(
            model_name='deck',
            name='language',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='cards.Language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(blank=True, to=b'cards.Card'),
        ),
    ]
