# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='see_also',
            field=models.ManyToManyField(blank=True, related_name='_card_see_also_+', to='cards.Card'),
        ),
    ]
