# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20161002_0532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='languages',
        ),
        migrations.AddField(
            model_name='person',
            name='languages',
            field=models.ManyToManyField(to='cards.Language'),
        ),
        migrations.AlterField(
            model_name='person',
            name='facebook_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
