# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20161002_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='language',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='cards.Language'),
            preserve_default=False,
        ),
    ]
