# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_deck_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='learning',
            field=models.ManyToManyField(blank=True, to='cards.Card'),
        ),
    ]
