# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20161002_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='learning',
        ),
    ]
