# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_auto_20161013_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='Michael Snook', max_length=200),
            preserve_default=False,
        ),
    ]
