# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_auto_20161013_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Language'),
        ),
    ]
