# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_auto_20161015_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='studying_languages',
        ),
    ]
