# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_remove_person_studying_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SlugField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_comment', models.TextField()),
                ('suggested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='deck',
            name='cards',
        ),
        migrations.AddField(
            model_name='deckmembership',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Deck'),
        ),
    ]
