# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_auto_20161023_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(through='cards.DeckMembership', to='cards.Card'),
        ),
    ]
