# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0017_deck_cards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='facebook_name',
            new_name='name',
        ),
    ]
